﻿﻿﻿spring.application.name=cooperpay
spring.datasource.url=jdbc:h2:file:${LOCALAPPDATA:${user.home}/.cooperpay}/CooperPay/data/cooperpay;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
logging.file.name=${LOCALAPPDATA:${user.home}/.cooperpay}/CooperPay/logs/cooperpay.log

# --- Asaas Pix API ---
# Sandbox: https://api-sandbox.asaas.com/v3
# Produção: https://api.asaas.com/v3/
asaas.api.base-url=https://api.asaas.com/v3/

# Busca o token na variável de ambiente ASAAS_TOKEN. 
# Se não existir, o valor fica vazio, disparando a validação no código.
asaas.api.access-token=${ASAAS_TOKEN:}
asaas.api.pix-descricao-padrao=Pagamento CooperPay via Pix
asaas.webhook.token=whsec_-OVyZJFVf9ez-JrT2r-tZd2czCDqZaowLNLFkeG17Rw

# --- Configurações Ngrok ---
# Token obtido em https://dashboard.ngrok.com/get-started/your-authtoken
ngrok.authtoken=3Ds9TwsFOIBtAwwR1fm9TM8PRZY_GDTKMS111LBRhMDZ2QE
# URL gerada pelo ngrok para referência (Ex: https://a1b2-c3d4.ngrok-free.app)
ngrok.public-url=https://viewing-swifter-diligence.ngrok-free.dev